# Generated by Django 4.1.3 on 2022-11-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_description_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Suppliers'),
        ),
    ]
